name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Configurar Python (necessário para o SNK)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerar animação da cobrinha
        uses: Platane/snk/svg-only@v3  # Corrigido para versão correta
        with:
          github_user_name: priscilla-neri
          outputs: |
            dist/g
